@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant CreateClassService as service <<application>>
participant Course as course <<domain>>
participant ExtraClass as extraClass <<domain>>
participant ScheduledDate as scheduleDate <<domain>>
participant Duration as duration <<domain>>
participant Date as date <<domain>>

activate service
service -> course: verifyIfExistAnExtraClassAtTheTime(startingDateWithTime, duration)
activate course

loop for all ExtraClass or until boolean == true
course -> extraClass: verifyIfExistAnExtraClassAtTheTime(startingDateWithTime, duration)
activate extraClass
extraClass -> scheduleDate: verifyIfExistAtTheCurrentTime(startingDateWithTime, duration)

activate scheduleDate
scheduleDate -> duration : returnMinutes()
activate duration
duration --> scheduleDate : thisDuration
deactivate duration
scheduleDate -> date : returnDate()
activate date
date --> scheduleDate : data_time
deactivate date

scheduleDate --> extraClass: boolean
deactivate scheduleDate
extraClass -->course: boolean
deactivate extraClass
end
course --> service: boolean
deactivate course
deactivate service
@enduml